name: DET_DyAGCN
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - conda-forge
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
dependencies:
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.5=py38h4cb3324_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=4.5.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h91455d4_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - arrow-cpp=16.1.0=h7cd61ee_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.6.21=h1ab79aa_0
  - aws-c-cal=0.5.20=h4b5e85a_3
  - aws-c-common=0.8.5=hcfcfb64_0
  - aws-c-compression=0.2.16=h3dc32ea_0
  - aws-c-event-stream=0.2.15=hd4acc35_11
  - aws-c-http=0.6.27=h844ee93_3
  - aws-c-io=0.13.11=hea55e33_2
  - aws-c-mqtt=0.7.13=h9ca50f7_9
  - aws-c-s3=0.2.1=hcdbbf7e_0
  - aws-c-sdkutils=0.1.7=h3dc32ea_0
  - aws-checksums=0.1.13=h3dc32ea_5
  - aws-crt-cpp=0.18.16=h6d7d590_2
  - aws-sdk-cpp=1.10.55=hd77b12b_0
  - babel=2.14.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.1.0=pyhd8ed1ab_0
  - bokeh=3.1.1=pyhd8ed1ab_0
  - boost-cpp=1.78.0=h5b4e17d_0
  - bottleneck=1.3.7=py38h9128911_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - brotli-python=1.0.9=py38hd77b12b_8
  - bzip2=1.0.8=h2466b09_7
  - c-ares=1.33.1=h2466b09_0
  - ca-certificates=2024.9.24=haa95532_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.8.30=py38haa95532_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=win_pyh7428d3b_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=py38haa95532_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.0.5=py38h59b6b97_0
  - cpython=3.8.20=py38hd8ed1ab_2
  - cuda-cccl=12.6.77=0
  - cuda-cccl_win-64=12.6.77=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.77=0
  - cuda-opencl-dev=12.6.77=0
  - cuda-profiler-api=12.6.77=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.3=py38h91455d4_0
  - dask=2023.5.0=pyhd8ed1ab_0
  - dask-core=2023.5.0=pyhd8ed1ab_0
  - datasets=2.14.4=pyhd8ed1ab_0
  - debugpy=1.8.5=py38h2698bfa_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.7=pyhd8ed1ab_0
  - distributed=2023.5.0=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - einops=0.8.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - filelock=3.13.1=py38haa95532_0
  - fonttools=4.51.0=py38h2bbff1b_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.4.1=py38h91455d4_0
  - fsspec=2024.9.0=pyhff2d567_0
  - gflags=2.2.2=he0c23c2_1005
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py38haa95532_0
  - glog=0.5.0=h4797de2_0
  - gmpy2=2.1.2=py38h7f96b67_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.6=pyhd8ed1ab_0
  - httpx=0.27.2=pyhd8ed1ab_0
  - huggingface_hub=0.25.1=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py38haa95532_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.0=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.12.2=pyh08f2357_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py38haa95532_0
  - joblib=1.4.2=py38haa95532_0
  - jpeg=9e=h827c3e9_3
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py38haa244fe_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh5737063_1
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py38hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20240116.2=cxx17_he0c23c2_1
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.7.77=0
  - libcurand-dev=10.3.7.77=0
  - libcurl=8.9.1=h0416ee5_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libevent=2.1.12=h3671451_1
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.62.2=hf25190f_0
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.17=h906ac69_0
  - libprotobuf=4.25.3=hf2fb9eb_0
  - libsodium=1.0.18=h8d14728_1
  - libssh2=1.10.0=h9a1e1f7_2
  - libthrift=0.15.0=h4364b78_2
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_1
  - lightning-utilities=0.11.7=pyhd8ed1ab_0
  - llvmlite=0.40.1=py38hf2fb9eb_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py38hb6d8784_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=2.1.3=py38h2bbff1b_0
  - matplotlib=3.7.2=py38haa95532_0
  - matplotlib-base=3.7.2=py38h4ed8f06_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py38haa95532_0
  - msgpack-python=1.0.8=py38h7b008d5_0
  - multidict=6.0.5=py38h91455d4_0
  - multiprocess=0.70.15=py38h91455d4_1
  - munch=4.0.0=pyhd8ed1ab_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.1=py38haa95532_0
  - notebook=7.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numba=0.57.1=py38hb182ae8_0
  - numexpr=2.8.4=py38h7b80656_1
  - numpy=1.24.3=py38h79a8e48_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - openssl=3.3.2=h2466b09_0
  - orc=2.0.1=hd8d391b_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.1=py38haa95532_0
  - pandas=2.0.3=py38h4ed8f06_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - partd=1.4.1=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.3.0=py38hdc2b20a_1
  - pip=24.2=py38haa95532_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=3.10.0=py38haa95532_0
  - ply=3.11=py38_0
  - pooch=1.7.0=py38haa95532_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_0
  - protobuf=4.25.3=py38h958608f_0
  - psutil=6.0.0=py38h4cb3324_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pyarrow=16.1.0=py38hc64d2fc_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=py38haa95532_0
  - pyqt=5.15.10=py38hd77b12b_0
  - pyqt5-sip=12.13.0=py38h2bbff1b_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.20=h8205438_0
  - python-dateutil=2.9.0post0=py38haa95532_2
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=1.4.4=py38h1e8a9f7_0
  - python_abi=3.8=2_cp38
  - pytorch=2.1.2=py3.8_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py38haa95532_0
  - pywin32=306=py38hd3f51b4_2
  - pywinpty=2.0.13=py38hd3f51b4_0
  - pyyaml=6.0.1=py38h2bbff1b_0
  - pyzmq=26.2.0=py38h3c56b06_0
  - qt-main=5.15.2=h19c9488_10
  - re2=2022.04.01=h0e60522_0
  - referencing=0.35.1=pyhd8ed1ab_0
  - regex=2024.7.24=py38h4cb3324_0
  - requests=2.32.3=py38haa95532_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.20.0=py38h2e0ef18_0
  - safetensors=0.4.4=py38h2e0ef18_0
  - scikit-learn=1.3.0=py38h4ed8f06_1
  - scipy=1.10.1=py38hdcfc7df_1
  - send2trash=1.8.3=pyh5737063_0
  - sentry-sdk=1.9.0=py38haa95532_0
  - setproctitle=1.2.2=py38h2bbff1b_1004
  - setuptools=75.1.0=py38haa95532_0
  - sip=6.7.12=py38hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=h23299a8_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py38he7056a7_0
  - stumpy=1.13.0=pyhd8ed1ab_0
  - sympy=1.13.2=py38haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tblib=3.0.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.5.0=py38h9909e9c_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.14=h0416ee5_0
  - tokenizers=0.20.0=py38hb80c39e_0
  - tomli=2.0.1=py38haa95532_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - torchmetrics=1.4.2=pyhd8ed1ab_0
  - tornado=6.4.1=py38h827c3e9_0
  - tqdm=4.66.5=py38h9909e9c_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - transformers=4.45.2=pyhd8ed1ab_0
  - tsfresh=0.20.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing-extensions=4.11.0=py38haa95532_0
  - typing_extensions=4.11.0=py38haa95532_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024a=h8827d51_1
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.1.0=py38h2bbff1b_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.3=py38haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.40.33810=ha82c5b3_21
  - vs2015_runtime=14.40.33810=h3bf8584_21
  - wandb=0.16.6=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.44.0=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - winpty=0.4.3=4
  - xyzservices=2024.9.0=pyhd8ed1ab_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - yarl=1.9.4=py38h91455d4_0
  - zeromq=4.3.5=he0c23c2_3
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.17.0=py38haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.5=hd43e919_2
  - pip:
      - adamp==0.3.0
      - cffi==1.17.1
      - chardet==5.2.0
      - jsonpatch==1.33
      - soundfile==0.12.1
      - torch-geometric==2.6.1
      - torchaudio==2.1.2
      - torchnet==0.0.4
      - torchvision==0.16.2
      - visdom==0.2.4
      - wfdb==4.1.2
prefix: \CondaEnvs\DET_DyAGCN
